import { filterDepartments, filterEmployees } from './filter.js';
import type { Department, DepartmentFilters, Employee, EmployeeFilters, EmployeeTasks } from './types.js';

// Mock rows shaped exactly like the real HRMS active-employee OData feed.
// Values are fabricated; the live feed returns the same field set.
export const SAMPLE_EMPLOYEES: readonly Employee[] = [
  {
    '@odata.etag': 'W/"sample-1001"',
    No: 'EMP-1001',
    Deputation_on: '',
    Sub_Province_Name: 'Kathmandu',
    Sub_Province_Code: 'KTM',
    Mobile_Phone_No: '9800000001',
    Department_Code: 'ENG',
    Company_E_Mail: 'aarav.sharma@example.com',
    Salary_Level: 'L5',
    Province_Name: 'Bagmati',
    Full_Name: 'Aarav Sharma',
    Department_Name: 'Engineering',
    Branch_Name: 'Head Office',
    Extension_Counter_Name: '',
    Unit_Name: 'Platform',
    Unit_Code: 'PLT',
    Functional_Title: 'Software Engineer',
    Province_Code: 'P3',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Software Engineer',
    Salary_Level_Description: 'Level 5',
    Branch_Code: 'HO',
    Blood_Group: 'O+',
  },
  {
    '@odata.etag': 'W/"sample-1002"',
    No: 'EMP-1002',
    Deputation_on: '',
    Sub_Province_Name: 'Pokhara',
    Sub_Province_Code: 'PKR',
    Mobile_Phone_No: '9800000002',
    Department_Code: 'HR',
    Company_E_Mail: 'maya.gurung@example.com',
    Salary_Level: 'L4',
    Province_Name: 'Gandaki',
    Full_Name: 'Maya Gurung',
    Department_Name: 'People Operations',
    Branch_Name: 'Pokhara Branch',
    Extension_Counter_Name: '',
    Unit_Name: 'HR Services',
    Unit_Code: 'HRS',
    Functional_Title: 'HR Specialist',
    Province_Code: 'P4',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Human Resources Specialist',
    Salary_Level_Description: 'Level 4',
    Branch_Code: 'PKR',
    Blood_Group: 'A+',
  },
  {
    '@odata.etag': 'W/"sample-1003"',
    No: 'EMP-1003',
    Deputation_on: '',
    Sub_Province_Name: 'Lalitpur',
    Sub_Province_Code: 'LTP',
    Mobile_Phone_No: '9800000003',
    Department_Code: 'SAL',
    Company_E_Mail: 'noah.williams@example.com',
    Salary_Level: 'L4',
    Province_Name: 'Bagmati',
    Full_Name: 'Noah Williams',
    Department_Name: 'Sales',
    Branch_Name: 'Head Office',
    Extension_Counter_Name: '',
    Unit_Name: 'Corporate Sales',
    Unit_Code: 'CSL',
    Functional_Title: 'Account Executive',
    Province_Code: 'P3',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Account Executive',
    Salary_Level_Description: 'Level 4',
    Branch_Code: 'HO',
    Blood_Group: 'B+',
  },
  {
    '@odata.etag': 'W/"sample-1004"',
    No: 'EMP-1004',
    Deputation_on: '',
    Sub_Province_Name: 'Biratnagar',
    Sub_Province_Code: 'BRT',
    Mobile_Phone_No: '9800000004',
    Department_Code: 'SAL',
    Company_E_Mail: 'sita.rai@example.com',
    Salary_Level: 'L3',
    Province_Name: 'Koshi',
    Full_Name: 'Sita Rai',
    Department_Name: 'Sales',
    Branch_Name: 'Biratnagar Branch',
    Extension_Counter_Name: '',
    Unit_Name: 'Retail Sales',
    Unit_Code: 'RSL',
    Functional_Title: 'Sales Officer',
    Province_Code: 'P1',
    Eco_System: 'Retail',
    Functional_Title_Desc: 'Sales Officer',
    Salary_Level_Description: 'Level 3',
    Branch_Code: 'BRT',
    Blood_Group: 'AB+',
  },
];

export function listSampleEmployees(filters: EmployeeFilters): Employee[] {
  return filterEmployees(SAMPLE_EMPLOYEES, filters);
}

// The real tasks feed always returns exactly one row that echoes the
// requested employee_id, with all-zero counts for an employee with nothing
// pending. Mirror that shape for the mock fallback.
export function sampleEmployeeTasks(employeeId: string): EmployeeTasks {
  return {
    primaryKey: '',
    To_Recommend_Attendance_Missed: 0,
    To_Approve_Attendance_Missed: 0,
    To_Recommend_Leave_Req: 0,
    To_Approve_Leave_Request: 0,
    To_Recommend_Travel_Req: 0,
    To_Approve_Travel_Req: 0,
    To_Recommend_Travel_Claim: 0,
    To_Approve_Travel_Claim: 0,
    To_Recommend_Transfer: 0,
    Incoming_Branch: 0,
    To_Review_Transfer: 0,
    To_Approve_Overtime: 0,
    To_Recommend_Overtime: 0,
    To_Recommend_Resignation: 0,
    To_Reviews_Resignation: 0,
    To_Recommend_Salary_Advance: 0,
    To_Recommend_Personal_Loan: 0,
    To_Recommend_Home_Loan: 0,
    To_Recommend_Vehicle_Loan: 0,
    To_Recommend_Allowance_Assig: 0,
    To_Recommend_Tranfer_Claim: 0,
    To_Review_Transfer_Claim: 0,
    Employee_Filter: employeeId,
  };
}

// Mock rows shaped exactly like the real HRMS departments feed.
export const SAMPLE_DEPARTMENTS: readonly Department[] = [
  {
    '@odata.etag': 'W/"sample-dept-001"',
    Code: 'ENG',
    Name: 'Engineering',
    Approver_Code: 'EMP-1005',
    Approver_Name: 'Priya Thapa',
    Approver_Code_Second: '',
    Approver_Name_Second: '',
    Skip_Attendance_Report: false,
    Blocked: false,
  },
  {
    '@odata.etag': 'W/"sample-dept-002"',
    Code: 'HR',
    Name: 'People Operations',
    Approver_Code: 'EMP-1006',
    Approver_Name: 'Ramesh Koirala',
    Approver_Code_Second: '',
    Approver_Name_Second: '',
    Skip_Attendance_Report: false,
    Blocked: false,
  },
  {
    '@odata.etag': 'W/"sample-dept-003"',
    Code: 'SAL',
    Name: 'Sales',
    Approver_Code: 'EMP-1007',
    Approver_Name: 'Anjali Basnet',
    Approver_Code_Second: '',
    Approver_Name_Second: '',
    Skip_Attendance_Report: false,
    Blocked: false,
  },
  {
    '@odata.etag': 'W/"sample-dept-004"',
    Code: 'LEG',
    Name: 'Legacy Operations',
    Approver_Code: '',
    Approver_Name: '',
    Approver_Code_Second: '',
    Approver_Name_Second: '',
    Skip_Attendance_Report: true,
    Blocked: true,
  },
];

export function listSampleDepartments(filters: DepartmentFilters): Department[] {
  return filterDepartments(SAMPLE_DEPARTMENTS, filters);
}
