import { filterEmployees } from './filter.js';
import type { Employee, EmployeeFilters } from './types.js';

// Mock rows shaped exactly like the real HRMS active-employee OData feed.
// Values are fabricated; the live feed returns the same field set.
export const SAMPLE_EMPLOYEES: readonly Employee[] = [
  {
    '@odata.etag': 'W/"sample-1001"',
    No: 'EMP-1001',
    Deputation_on: '',
    Sub_Province_Name: 'Kathmandu',
    Sub_Province_Code: 'KTM',
    Mobile_Phone_No: '9800000001',
    Department_Code: 'ENG',
    Company_E_Mail: 'aarav.sharma@example.com',
    Salary_Level: 'L5',
    Province_Name: 'Bagmati',
    Full_Name: 'Aarav Sharma',
    Department_Name: 'Engineering',
    Branch_Name: 'Head Office',
    Extension_Counter_Name: '',
    Unit_Name: 'Platform',
    Unit_Code: 'PLT',
    Functional_Title: 'Software Engineer',
    Province_Code: 'P3',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Software Engineer',
    Salary_Level_Description: 'Level 5',
    Branch_Code: 'HO',
    Blood_Group: 'O+',
  },
  {
    '@odata.etag': 'W/"sample-1002"',
    No: 'EMP-1002',
    Deputation_on: '',
    Sub_Province_Name: 'Pokhara',
    Sub_Province_Code: 'PKR',
    Mobile_Phone_No: '9800000002',
    Department_Code: 'HR',
    Company_E_Mail: 'maya.gurung@example.com',
    Salary_Level: 'L4',
    Province_Name: 'Gandaki',
    Full_Name: 'Maya Gurung',
    Department_Name: 'People Operations',
    Branch_Name: 'Pokhara Branch',
    Extension_Counter_Name: '',
    Unit_Name: 'HR Services',
    Unit_Code: 'HRS',
    Functional_Title: 'HR Specialist',
    Province_Code: 'P4',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Human Resources Specialist',
    Salary_Level_Description: 'Level 4',
    Branch_Code: 'PKR',
    Blood_Group: 'A+',
  },
  {
    '@odata.etag': 'W/"sample-1003"',
    No: 'EMP-1003',
    Deputation_on: '',
    Sub_Province_Name: 'Lalitpur',
    Sub_Province_Code: 'LTP',
    Mobile_Phone_No: '9800000003',
    Department_Code: 'SAL',
    Company_E_Mail: 'noah.williams@example.com',
    Salary_Level: 'L4',
    Province_Name: 'Bagmati',
    Full_Name: 'Noah Williams',
    Department_Name: 'Sales',
    Branch_Name: 'Head Office',
    Extension_Counter_Name: '',
    Unit_Name: 'Corporate Sales',
    Unit_Code: 'CSL',
    Functional_Title: 'Account Executive',
    Province_Code: 'P3',
    Eco_System: 'Corporate',
    Functional_Title_Desc: 'Account Executive',
    Salary_Level_Description: 'Level 4',
    Branch_Code: 'HO',
    Blood_Group: 'B+',
  },
  {
    '@odata.etag': 'W/"sample-1004"',
    No: 'EMP-1004',
    Deputation_on: '',
    Sub_Province_Name: 'Biratnagar',
    Sub_Province_Code: 'BRT',
    Mobile_Phone_No: '9800000004',
    Department_Code: 'SAL',
    Company_E_Mail: 'sita.rai@example.com',
    Salary_Level: 'L3',
    Province_Name: 'Koshi',
    Full_Name: 'Sita Rai',
    Department_Name: 'Sales',
    Branch_Name: 'Biratnagar Branch',
    Extension_Counter_Name: '',
    Unit_Name: 'Retail Sales',
    Unit_Code: 'RSL',
    Functional_Title: 'Sales Officer',
    Province_Code: 'P1',
    Eco_System: 'Retail',
    Functional_Title_Desc: 'Sales Officer',
    Salary_Level_Description: 'Level 3',
    Branch_Code: 'BRT',
    Blood_Group: 'AB+',
  },
];

export function listSampleEmployees(filters: EmployeeFilters): Employee[] {
  return filterEmployees(SAMPLE_EMPLOYEES, filters);
}
